<a href="https://colab.research.google.com/github/coding-dojo-data-science/python-basics-notebooks/blob/main/Working_with_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Arrays

In this notebook you will 
1. import the NumPy Python package, 
2. create a NumPy array.
3. access data in a NumPy Array

# 1. Importing NumPy

You've learned how to create custom functions in Python, but you can also import functions that other people have made.  This will become a core part of your work in the program and you'll notice that the number of custom packages you import will grow as you learn to use new tools.

Today we will only import one custom package: NumPy, which is called `numpy` in Python code.

They NumPy package is already saved in Colab, so you won't need to download it. However, if you are using this notebook at home, you may need to download this package onto your hard drive.  You can do this with the code: `!pip install numpy`

1. We start by using the keyword `import` to tell Python we are importing a package. Note that downloading and importing are different!

2. Then we tell Python with package we want to import: `numpy`.

3. Next we will give NumPy the alias `np`.  In order to access functions in the numpy package, we will need to put the name of the package first, like `numpy.array()`.  However, since we will be using NumPy a lot, we can give the package a nickname, also called an 'alias'.  We do that with the `as` keyword.  It's tradition to alias NumPy as `np`.

Putting these together we type:

`import numpy as np`

Type this code in he cell below and then press shift-enter to run the cell.  Once you've done that NumPy will be loaded and you can start using its functions.

In [ ]:
import numpy as np

# 2. Creating a NumPy Array

## a. 1-dimensional arrays
There are many ways to create arrays and often in your work as a data science you will be loading outside datasets into your Python environment.  Today, however, we will generate some data using the `range()` function and then convert it into an array.

1. Declare a variable, `data` and point it to a range object with numbers between 0 and 19. 

2. Change the type of this range object to a list so that you can verify it has the right numbers. 

**Hint** you can use `range()` and pass it an argument to tell it the numbers you want.  In Python, ranges start at 0 and exclude the highest number.

3. Print the result.  You should have a list of numbers from 0 to 19.

In [ ]:
data = range(20)
data = list(data)
print(data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


You should now have a list named `data` with the numbers 0 to 19.  Let's change it to an array!

You can use the function `np.array()` to change a Python collection into a NumPy array.

Chage the type of data into an `ndarray` and print out the result.  The result should look like a list with no commas.

In [ ]:
data = np.array(data)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


You created a 1-dimensional array by creating a range object, converting it into a list, and then converting the list into an array.  You could have also converted the range object directly into an array.  Notice that the array looks a lot like a list, and we can treat it like a list.

Arrays are ordered and mutable, just like lists, but they are faster to and more efficient to store in memory.

## b. 2-dimensional arrays

Do you remember that lists can contain other lists?  You can create a 2-dimensional array using a list of lists!  The only trick is that all the lists have to be the same length.

1. Create 2 new arrays.  Call them `array1` and `array2`.  

The first array should have numbers 0 to 19, and the second list should have numbers 20 to 39.  Remember that you can do this quickly by using a range object.

**Hint** 

You can give a range object 2 arguments.  It will start the numbers at the first argument and end at one number before the second argument.

2. Create a new list that contains the previous 2 lists as elements.  Call the new list `data2d`.

3. Convert `data2d` to an ndarray.

4. Print `data2d`.

In [ ]:
list1 = np.array(range(20))
list2 = np.array(range(20,40))

data2d = [list1, list2]
data2d = np.array(data2d)
print(data2d)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]]


Your result should look like a stack of lists with no commas, one on top with numbers 0 to 19 and one on bottom with numbers 20 to 29.

If so, nice work!  You created a 2-dimensional array!

You could keep making higher dimensional arrays by nesting lists inside lists inside lists, etc.

# 3. Accessing Data in an Array

Accessing data in an array is very similar to accessing data in a list or tupe.  You use the `[]` notation with the index of the item you want inside the brackets.

Print the 9th data point in the array named `data`

**Hint** Python indices start at 0, so the first element is at index 0.

In [ ]:
print(data[8])

8


If your code above output the number `8`, you did it right!

Next let's access data in a 2-dimensional array.  These are the kinds of arrays that you will mostly working with in this program.  You can think of a spreadsheet as a 2-dimensional array.  We will access by defining the row and column that the data we want is located.

To access data in a 2-dimensional array, you use 2 sets of numbers in brackets.  The first one describes where on the first axis your data is located and the second defines where on the second axis it is.

Notice that this is similar to accessing a 1-dimensional array, with another set of brackets.

But, to start, let's just try using one set of brackets with a 2-dimensional array and see what happens.

1. Print the second element in the array called `data2d` and display it. Remember that Python indices start with 0.

In [ ]:
print(data2d[1])

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


If your code above output an array with the numbers 20 though 39, you did it right!

2. Now access the 5th element of the second element of `data2d`.  That would be the 5th column of the second row.

In [ ]:
print(data2d[1][4])

24


Your code should have output the number `24`.  If so, you've completed this lesson!

# Summary

In this lesson you learned how to create one and two dimensional NumPy arrays using range objects and lists.  You also learned to access data in NumPy arrays through indexing.